# Generated by Django 4.1.3 on 2022-12-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_services', '0004_alter_customer_options_alter_salonservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('user__first_name',), 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
