# Generated by Django 4.1.3 on 2022-12-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_services', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content', models.TextField(max_length=1000, verbose_name='content')),
                ('beauty_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beauty_services.beautysalon', verbose_name='beauty salon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beauty_services.customer', verbose_name='customer')),
            ],
        ),
    ]
